function printStatsReport(report) {
  console.log("\n=== INZ GitHub Stats ===\n");
  console.log(`User:     @${report.username}`);
  console.log(`URL:      ${report.profile.url}`);
  console.log(`Name:     ${report.profile.name || "—"}`);
  console.log(`Bio:      ${report.profile.bio || "—"}`);
  console.log(`Joined:   ${report.profile.createdAt} (${report.accountAgeDays} days ago)`);
  console.log(`Followers: ${report.profile.followers}  |  Following: ${report.profile.following}`);
  console.log("");

  console.log("--- Activity (last 90 days) ---");
  console.log(`Events:       ${report.recentActivity.count}`);
  console.log(`Types:        ${report.recentActivity.types.join(", ") || "none"}`);
  console.log(`Merged PRs:   ${report.mergedPrs} (to third-party repos, 12 months)`);
  console.log("");

  console.log("--- Repository Portfolio ---");
  console.log(`Public repos: ${report.repoStats.totalPublic}`);
  console.log(`Total stars:  ${report.repoStats.totalStars}`);
  console.log(`Licensed:     ${report.repoStats.licensed}`);
  console.log(`Top external contributors: ${report.repoStats.topContributors}${report.repoStats.topContributorRepo ? ` (${report.repoStats.topContributorRepo})` : ""}`);
  console.log("");

  if (report.repoStats.topRepos.length > 0) {
    console.log("--- Top Repositories ---");
    for (const repo of report.repoStats.topRepos) {
      console.log(`  ${repo.name}`);
      console.log(`    stars: ${repo.stars}  |  lang: ${repo.language}  |  license: ${repo.license}`);
    }
    console.log("");
  }

  console.log("Generated by INZ Ecosystem — https://github.com/fahnovinz/inz-ecosystem\n");
}

module.exports = { printStatsReport };